#ifndef __TRAFFIC_MIRROR_ERRNO_H_
#define __TRAFFIC_MIRROR_ERRNO_H_

enum errno {
	E_UNKNOWN = 0,

	E_BPF_PROBE_READ_FAILED,
	E_BPF_MAP_LOOKUP_ELEM_FAILED,

	E_READ_SOCKET_INFO_FAILED,
	E_SOCK_DATA_TRUNCATED,
	E_IOV_ITER_TYPE_ERROR,
	E_IOV_DATA_TOO_LONG,
	E_IOV_OFFSET_TOO_BIG,
	E_PERF_EVENT_TOO_LONG,
};

#endif // __TRAFFIC_MIRROR_ERRNO_H_
